apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-sidecar
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html

  - name: sidecar-logger
    image: busybox
    command: ["sh", "-c"]
    args:
      - while true; do echo "Hello from sidecar"; sleep 10; done

  initContainers:
  - name: init-content
    image: busybox
    command: ["sh", "-c"]
    args:
      - |
        echo '<html><body><h1>Hello from NGINX!</h1></body></html>' > /html/index.html
    volumeMounts:
    - name: html
      mountPath: /html

  volumes:
  - name: html
    emptyDir: {}





